#!/bin/sh
INSTALLROOT=D:/installs/demoE
export INSTALLROOT
JAVA_HOME=C:/j2sdk1.4.2_03
export JAVA_HOME
JAVAVM=java
export JAVAVM
VBROKER_HOME=C:/BDP
export VBROKER_HOME
JACORB_HOME=<JACORB_HOME>
export JACORB_HOME
if [ -f $INSTALLROOT/nfienv.sh ] ; then
  . $INSTALLROOT/nfienv.sh
fi
OAD_PORT=16101
export OAD_PORT
OSAGENT_ADDR=192.168.97.83
export OSAGENT_ADDR
OSAGENT_PORT=14101
export OSAGENT_PORT
RMIPort=1099
export RMIPort
DBNAME=jdbc:oracle:thin:@192.168.97.97:1521:nstar
export DBNAME
DBUSER=depdemoE
export DBUSER
JAVA_OPTS="$JAVA_OPTS -Xmx500m -Xms100m "
export JAVA_OPTS   

CLASSPATH=<CLASSPATH>:
CLASSPATH=$NFICLASSPATH:$CLASSPATH:$NMICLASSPATH
export CLASSPATH